# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AddressToPolygon
                                 A QGIS plugin
 get polygon by address
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-02
        copyright            : (C) 2025 by Bezdares
        email                : bezdares@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import pip
from qgis.PyQt.QtWidgets import QDockWidget
from qgis.utils import iface
from console.console import show_console 

def classFactory(iface):  # pylint: disable=invalid-name
    try:
        import overpy
        import geopy
        import pandas
    except ImportError:
        open_python_console()
        pip.main(["install", "overpy", "geopy", "pandas", "--user"])

    from .get_polygon import AddressToPolygon
    return AddressToPolygon(iface)


def open_python_console():
    console = iface.mainWindow().findChild(QDockWidget, "PythonConsole")
    if not console:
        show_console()