# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AddressToPolygon
                                 A QGIS plugin
 get polygon by address
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-02
        copyright            : (C) 2025 by Bezdares
        email                : bezdares@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

# noinspection PyPep8Naming
import os
import sys

plugin_dir = os.path.dirname(__file__)
libs_path = os.path.join(plugin_dir, 'libs')
if libs_path not in sys.path:
    sys.path.insert(0, libs_path)


def classFactory(iface):  # pylint: disable=invalid-name
    """Load AddressToPolygon class from file AddressToPolygon."""

    from .get_polygon import AddressToPolygon
    return AddressToPolygon(iface)

