# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AddressToPolygon
                                 A QGIS plugin
 get polygon by address
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-02
        copyright            : (C) 2025 by Bezdares
        email                : bezdares@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import subprocess
import sys


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AddressToPolygon class from file AddressToPolygon.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    install_packages()

    from .get_polygon import AddressToPolygon
    return AddressToPolygon(iface)


REQUIRED_PACKAGES = ["geopy", "overpy", "pandas"]

def install_packages():
    for package in REQUIRED_PACKAGES:
        try:
            __import__(package)
        except ImportError:
            try:
                subprocess.check_call([sys.executable, "-m", "pip", "install", package])
            except Exception as e:
                print(f"Ошибка установки {package}: {e}")
